function [Sepallength, Sepalwidth, Petallength, Petalwidth, Irissetosa1] = importIrisDataset

%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/nuno/Nuno/ISEL/Ensino/Ano 19-20/Verao/IA/Lectures/Week14/Lecture-35-36/iris/iris.data
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2020/06/03 20:35:45

%% Initialize variables.
filename = '/home/nuno/Nuno/ISEL/Ensino/Ano 19-20/Verao/IA/Lectures/Week14/Lecture-35-36/iris/iris.data';
delimiter = ',';

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Sepallength = dataArray{:, 1};
Sepalwidth = dataArray{:, 2};
Petallength = dataArray{:, 3};
Petalwidth = dataArray{:, 4};
Irissetosa1 = dataArray{:, 5};


%% Clear temporary variables
%clearvars filename delimiter formatSpec fileID dataArray ans;


end
